### PR TITLE
Add Whisper AI model -->  Hindi to English

### PR DESCRIPTION
**Pull request by atharvapurdue**
Adding Whisper AI Model which successfully translated a Hindi  language short YouTube video clip to English text.
This English text was then saved as a VTT file format (subtitle file), to integrate with the original video clip
The flow was as follows - 
Hindi Video Clip --> Hindi Audio Clip --> Hindi Language detected by Open AI Whisper --> Hindi to English Text Conversion by OpenAI Whisper --> English Subtitles file created for the original Hindi video clip 

Open AI Whisper Architecture 
approach_whisper

Note - the input YouTube video already has English subtitles - I chose this video to allow non-hindi speakers to understand what is there in the video.
Whisper AI has coverage for a lot of languages - 
language-breakdown
According to me, we are getting about 95 % accurate translation for this particular video clip

Further work is required in the following - 
1. creating audio file from English text file
2.  Testing out Whisper AI for other models (I currently used the "medium" version), and also other languages (eg - Chinese, spanish etc)
Reference links - 
1. https://github.com/openai/whisper 
3. https://www.youtube.com/watch?v=x_uxzgTg1U0

### CODE REVIEW

**Comment by yash-1708** [comment]
Dev Notes : We need to focus on improving the accuracy for the languages that it is low for. Hindi translation worked well with some minor grammatical mistakes. We can also consider using a english grammar-checking API to remedy this in the future.

**Review by yash-1708 — APPROVED** [review]
Code looks great! Please look at my comment on the thread for dev notes. Approving this as research

**Comment by zeshengchen** [comment]
The jupyter notebook contains several errors in the file. Please fix them!

**Comment by atharvapurdue** [comment]
> The jupyter notebook contains several errors in the file. Please fix them! @zeshengchen 
The error part has been removed. 
The notebook is fully functional. Please let me know if there are any other changes required.

**Comment by zeshengchen** [comment]
For the pull request, it is better to remove the useless files and the commented-out code in the code.

**Comment by zeshengchen** [comment]
Moreover, it is better to keep the outputs in the jupyter notebook so that other people can see the results without having to run it.

**Review by marktrovinger — APPROVED** [review]

**Review by winniehar — APPROVED** [review]

**Pull request closed without merging**
