### PR TITLE
Research

### PR DESCRIPTION
**Pull request by winniehar**
Deepspeech - comparing the transcripts generated and actual speech, the accuracy of deep speech doesn't look too good.
Also uploaded the email communication with one Taiwan professor who had his Chinese lecture series translated to English. According to him, his TA had to do a lot of manually edit after using EZyoutuber (pay to use).

### CODE REVIEW

**Review by marktrovinger — APPROVED** [review]
Thank you for checking this out, I knew this project was going to be a battle, and this isn't changing my mind at all.

**Comment by zeshengchen** [comment]
As I talked to Winnie today, for this project, please consider first to build the prototyping of the system, without considering the performance. After it is working from audio (or over the air) to playing the translated speech end to end, then consider how to improve the accuracy.

**Review by atharvapurdue — APPROVED** [review]
Thank you for the commit @winniehar

**Comment by yash-1708** [comment]
Looks great, I have reviewed the code with Atharva on his laptop

**Pull request merged**
