### PR TITLE
added first draft of UI

### PR DESCRIPTION
**Pull request by yash-1708**
We will update this going ahead according to the features we eventually en dup implementing.
The link to the editable figma file is [here](https://www.figma.com/file/KOVjaP2iyhpQScuHr4d9mt/Untitled?node-id=0%3A1)

### CODE REVIEW

**Review by winniehar — APPROVED** [review]

**Review by marktrovinger — APPROVED** [review]
Looks good, as you mentioned we can always iterate.

**Comment by zeshengchen** [comment]
It looks like that this pull request was merged without all approvals?

**Comment by atharvapurdue** [comment]
I had approved it, but it is not reflecting here for some reason

**Comment by zeshengchen** [comment]
@atharvapurdue

**Pull request merged**
