### PR TITLE
adding more open-source models we reviewed to README

### PR DESCRIPTION
**Pull request by atharvapurdue**

### CODE REVIEW

**Review by yash-1708 — APPROVED** [review]

**Review by winniehar — COMMENTED** [review]
Can you provide the output of any models/API in the list?

**Comment by atharvapurdue** [comment]
> Can you provide the output of any models/API in the list?

Yes,
I have just added it to readme to show the models we are exploring
@yash-1708  and I are working on some of these models, we will update the research branch once the results are ready in the future

**Review by marktrovinger — COMMENTED** [review]
There are some small grammatical errors, line 20, Brieft instead of brief for instance, but overall the changes expand the documentation quite a bit.

**Comment by winniehar** [comment]
> > Can you provide the output of any models/API in the list?
> 
> Yes, I have just added it to readme to show the models we are exploring @yash-1708 and I are working on some of these models, we will update the research branch once the results are ready in the future

Could you add status to say which ones have been tested and which ones are still being worked on?

**Comment by atharvapurdue** [comment]
> > > Can you provide the output of any models/API in the list?
> > 
> > 
> > Yes, I have just added it to readme to show the models we are exploring @yash-1708 and I are working on some of these models, we will update the research branch once the results are ready in the future
> 
> Could you add status to say which ones have been tested and which ones are still being worked on?

sure!

**Comment by atharvapurdue** [comment]
> There are some small grammatical errors, line 20, Brieft instead of brief for instance, but overall the changes expand the documentation quite a bit. Also, make sure to not delete the branch, as we can use this branch again in the future.

sure! I will make these changes

**Pull request closed without merging**
