### PR TITLE
Flask api

### PR DESCRIPTION
**Pull request by marktrovinger**
Starting point for building the flask API. I am creating an issue that we can work against, but I wanted to get the code merged so we have a starting point.

### CODE REVIEW

**Review by atharvapurdue — APPROVED** [review]
good starting point

**Review by zeshengchen — APPROVED** [review]
I approved this pull request, but have a question: will web service be better for the project? What is your reasoning here? How about other options such as desktop application?

**Comment by marktrovinger** [comment]
@zeshengchen those are good questions, and while a web app would seem to be the "default" option, I did consider other options. The main reason for a web app is that it will allow our group to run a model with a higher level of performance without having to rely upon the user's machine (the model can run on colab for instace). The second reason for a web app is that it allows us to make a "mobile friendly" version without having to actually create separate iOS and Android versions, at least at this stage (this can be revisited, but it doesn't lock us into anything). Since the main use case for translation software is in a less formal setting, a user can have the web app running on their phone while having the conversation. If they need to use it in a more formal setting (class for instance), they can use a laptop in a similar fashion.

**Comment by zeshengchen** [comment]
> @zeshengchen those are good questions, and while a web app would seem to be the "default" option, I did consider other options. The main reason for a web app is that it will allow our group to run a model with a higher level of performance without having to rely upon the user's machine (the model can run on colab for instance). The second reason for a web app is that it allows us to make a "mobile friendly" version without having to actually create separate iOS and Android versions, at least at this stage (this can be revisited, but it doesn't lock us into anything). Since the main use case for translation software is in a less formal setting, a user can have the web app running on their phone while having the conversation. If they need to use it in a more formal setting (class for instance), they can use a laptop in a similar fashion.

Thanks for the reply! Please consider the environment where your project will be applied, such as real-time translating a long talk or real-time conversation. I am particularly interested in the case that is real-time translation of a long talk. One main concern to apply web based is the delay on the transmissions between web client and web server. But the good part of web based is that if the web server is with GPU, it will improve the translation speed a lot. I agree with you that please explore different options to see which one is best.

**Review by yash-1708 — APPROVED** [review]

**Review by winniehar — APPROVED** [review]

**Pull request merged**
